# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://skatesapp.wordpress.com/privacy/                                       # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
terms_download_link                       : includes/terms.html  #https://skatesapp.wordpress.com/terms-of-use/
FAQ_download_link                         : https://skatesapp.wordpress.com/frequently-asked-questions/
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/Icon-App-1024x1024.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Skates                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Start your subscription now                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A Base Value Calculator for Figure Skating, Pairs, Ice Dance, and Solo Ice Dance.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                            
your_link                                 :               
your_city                                 :                                
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Score any program
    description                           : Designed to score any program, for any skater, anywhere.
    fontawesome_icon_name                 : magic
    
  - title                                 : Made for iPhone
    description                           : Skates has been built exclusively for iPhone.
    fontawesome_icon_name                 : mobile

  - title                                 : Smart
    description                           : No need to understand how scores are calculated. Simply enter your elements, and let Skates do all the work.
    fontawesome_icon_name                 : brain

  - title                                 : Continuosly Updated
    description                           : Skates is regularly kept up to date with all ISU scales of values.
    fontawesome_icon_name                 : sync

  - title                                 : Grade of Execution
    description                           : Although not required, Skates can adjust values with Grade of Execution (GOE) values, if you would like to gain a complete element score.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Look up
    description                           : You can grab a quick look at a particular element, just by searching for it. You can even apply levels, and GOE values and see, live, how you can build your score.
    fontawesome_icon_name                 : search

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

#Terms List

terms                                     :

  - title                                 :Test Title
  - description                           :Test description

# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 0.1
topbar_title_color                        : "#000000"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#666666"
cover_overlay_transparency                : 0.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "1d63ea"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#666666"
app_description_color                     : "#666666"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ff2d55"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#ffffff"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
